-- ****************** SqlDBM: Microsoft SQL Server ******************
-- ******************************************************************
-- ************************************** [dbo].[magento_1]


-- Old Schema
CREATE TABLE [dbo].[magentoV1_prod]
(
 [domain]                       VARCHAR(150) NOT NULL ,
 [url]                          VARCHAR(150) NOT NULL ,
 [overallvisits]                VARCHAR(50) NULL ,
 [timeonsite]                   VARCHAR(50) NULL ,
 [pagesperVisit]                DECIMAL(10,2) NULL ,
 [bouncerate]                   DECIMAL(5,2) NULL ,
 [displayads]                   INT NULL ,
 [world_rank]                   NUMERIC(10,0) NULL ,
 [world_rank_change]            VARCHAR(50) NULL ,
 [country_rank]                 NUMERIC(10,0) NULL ,
 [country_top]                  VARCHAR(30) NULL ,
 [country_rank_change]          NUMERIC(10,0) NULL ,
 [category_rank]                NUMERIC(10,0) NULL ,
 [category_top]                 VARCHAR(50) NULL ,
 [trafficsources.Social]        DECIMAL(18,8) NULL ,
 [trafficsources.DisplayAds]    DECIMAL(18,8) NULL ,
 [trafficsources.Mail]          DECIMAL(18,8) NULL ,
 [trafficsources.PaidSearch]    DECIMAL(18,8) NULL ,
 [trafficsources.Referrals]     DECIMAL(18,8) NULL ,
 [trafficsources.OrganicSearch] DECIMAL(18,8) NULL ,
 [trafficsources.Direct]        DECIMAL(18,8) NULL ,
 [trafficcountry.countryName_1] VARCHAR(50) NULL ,
 [trafficcountry.countryName_2] VARCHAR(50) NULL ,
 [trafficcountry.countryName_3] VARCHAR(50) NULL ,
 [trafficcountry.countryName_4] VARCHAR(50) NULL ,
 [trafficcountry.countryName_5] VARCHAR(50) NULL ,
 [trafficcountry.change_1]      DECIMAL(18,8) NULL ,
 [trafficcountry.change_2]      DECIMAL(18,8) NULL ,
 [trafficcountry.change_3]      DECIMAL(18,8) NULL ,
 [trafficcountry.change_4]      DECIMAL(18,8) NULL ,
 [trafficcountry.change_5]      DECIMAL(18,8) NULL ,
 [trafficcountry.value_1]       DECIMAL(18,8) NULL ,
 [trafficcountry.value_2]       DECIMAL(18,8) NULL ,
 [trafficcountry.value_3]       DECIMAL(18,8) NULL ,
 [trafficcountry.value_4]       DECIMAL(18,8) NULL ,
 [trafficcountry.value_5]       DECIMAL(18,8) NULL ,
 [visitData.date_1]             VARCHAR(15) NULL ,
 [visitData.date_2]             VARCHAR(15) NULL ,
 [visitData.date_3]             VARCHAR(15) NULL ,
 [visitData.date_4]             VARCHAR(15) NULL ,
 [visitData.date_5]             VARCHAR(15) NULL ,
 [visitData.count_1]            NUMERIC(18,0) NULL ,
 [visitData.count_2]            NUMERIC(18,0) NULL ,
 [visitData.count_3]            NUMERIC(18,0) NULL ,
 [visitData.count_4]            NUMERIC(18,0) NULL ,
 [visitData.count_5]            NUMERIC(18,0) NULL ,
 [social.facebook]              DECIMAL(18,8) NULL ,
 [social.youtube]               DECIMAL(18,8) NULL ,
 [social.reddit]                DECIMAL(18,8) NULL ,
 [social.pinterest]             DECIMAL(18,8) NULL ,
 [social.twitter]               DECIMAL(18,8) NULL ,
 [social.instagram]             DECIMAL(18,8) NULL ,
 [social.quora]                 DECIMAL(18,8) NULL ,
 [social.others]                DECIMAL(18,8) NULL ,
 [social.vk]                    DECIMAL(18,8) NULL ,
 [social.whatsapp]              DECIMAL(18,8) NULL ,
 [category]                     TEXT NULL ,

	PRIMARY KEY CLUSTERED ([domain] ASC)
);

-- New Schema
CREATE TABLE [dbo].[magentoV2_test]
(
	[domain]							VARCHAR(150) NOT NULL,
	[overallvisits]						NUMERIC(10,0) NULL,
	[timeonsite]						VARCHAR(50) NULL,
	[pagesperVisit]						DECIMAL(18,8) NULL,
	[bouncerate]						NUMERIC(10,0) NULL,
	[world_rank]						NUMERIC(10,0) NULL,
	[country_rank]						NUMERIC(10,0) NULL,
	[country_top]						VARCHAR(30) NULL ,
	[category_rank]						NUMERIC(10,0) NULL,
	[category_top]						VARCHAR(100) NULL ,
	[trafficsources.Social]				DECIMAL(18,8) NULL,
	[trafficsources.DisplayAds] 		DECIMAL(18,8) NULL,
	[trafficsources.Mail]				DECIMAL(18,8) NULL,
	[trafficsources.PaidSearch] 		DECIMAL(18,8) NULL,
	[trafficsources.Referrals]			DECIMAL(18,8) NULL,
	[trafficsources.OrganicSearch] 		DECIMAL(18,8) NULL,
	[trafficsources.Direct]				DECIMAL(18,8) NULL,
	[trafficcountry.countryName_1] 		VARCHAR(30) NULL ,
	[trafficcountry.countryName_2] 		VARCHAR(30) NULL ,
	[trafficcountry.countryName_3]		VARCHAR(30) NULL ,
	[trafficcountry.countryName_4]		VARCHAR(30) NULL ,
	[trafficcountry.countryName_5]		VARCHAR(30) NULL ,
	[trafficcountry.value_1]			DECIMAL(18,8) NULL,
	[trafficcountry.value_2]			DECIMAL(18,8) NULL,
	[trafficcountry.value_3]			DECIMAL(18,8) NULL,
	[trafficcountry.value_4]			DECIMAL(18,8) NULL,
	[trafficcountry.value_5]			DECIMAL(18,8) NULL,
	[visitData.date_1]					VARCHAR(30) NULL ,
	[visitData.date_2]					VARCHAR(30) NULL ,
	[visitData.date_3]					VARCHAR(30) NULL ,
	[visitData.count_1]					NUMERIC(10,0) NULL,
	[visitData.count_2]					NUMERIC(10,0) NULL,
	[visitData.count_3]					NUMERIC(10,0) NULL,
	[facebook]							DECIMAL(18,8) NULL ,
	[youtube]							DECIMAL(18,8) NULL ,
	[reddit]							DECIMAL(18,8) NULL ,
	[pinterest]							DECIMAL(18,8) NULL ,
	[instagram]							DECIMAL(18,8) NULL ,
	[quora]								DECIMAL(18,8) NULL ,
	[others]							DECIMAL(18,8) NULL ,
	[vk]								DECIMAL(18,8) NULL ,
	[whatsapp]							DECIMAL(18,8) NULL ,
	[linkedin]							DECIMAL(18,8) NULL ,
	[referring_domains]					TEXT NULL,
	PRIMARY KEY CLUSTERED ([domain] ASC)
);



